export const dataBuku = [
  {
    no: "1",
    id: "B0001",
    judul: "In ornare sagittis",
    pengarang: "Griffin Norton",
    penerbit: "Nunc Id Enim Associates",
    tahun: "2022",
  },
  {
    no: "2",
    id: "B0002",
    judul: "non justo. Proin",
    pengarang: "Keaton Daniels",
    penerbit: "Egestas PC",
    tahun: "2022",
  },
  {
    no: "3",
    id: "B0003",
    judul: "Morbi sit amet",
    pengarang: "Clio Conley",
    penerbit: "Ante Lectus Ltd",
    tahun: "2022",
  },
  {
    no: "4",
    id: "B0004",
    judul: "eu, eleifend nec,",
    pengarang: "Kylan Baird",
    penerbit: "Vel Mauris Associates",
    tahun: "2022",
  },
  {
    no: "5",
    id: "B0005",
    judul: "Sed eget lacus.",
    pengarang: "Jessica Hess",
    penerbit: "Quam Curabitur LLP",
    tahun: "2022",
  },
  {
    no: "6",
    id: "B0006",
    judul: "et, magna. Praesent",
    pengarang: "Teagan Ferrell",
    penerbit: "Massa Associates",
    tahun: "2022",
  },
  {
    no: "7",
    id: "B0007",
    judul: "libero et tristique",
    pengarang: "Ross Mcbride",
    penerbit: "Libero Incorporated",
    tahun: "2022",
  },
  {
    no: "8",
    id: "B0008",
    judul: "Aenean massa. Integer",
    pengarang: "Pascale Thornton",
    penerbit: "Ante Dictum Foundation",
    tahun: "2022",
  },
  {
    no: "9",
    id: "B0009",
    judul: "Nullam feugiat placerat",
    pengarang: "Madonna Brown",
    penerbit: "Mauris Nulla Inc.",
    tahun: "2022",
  },
  {
    no: "10",
    id: "B00010",
    judul: "tortor, dictum eu,",
    pengarang: "Burke Pacheco",
    penerbit: "Torquent Per Foundation",
    tahun: "2022",
  },
  {
    no: "11",
    id: "B0011",
    judul: "In ornare sagittis",
    pengarang: "Griffin Norton",
    penerbit: "Nunc Id Enim Associates",
    tahun: "2022",
  },
  {
    no: "12",
    id: "B0012",
    judul: "non justo. Proin",
    pengarang: "Keaton Daniels",
    penerbit: "Egestas PC",
    tahun: "2022",
  },
  {
    no: "13",
    id: "B0013",
    judul: "Morbi sit amet",
    pengarang: "Clio Conley",
    penerbit: "Ante Lectus Ltd",
    tahun: "2022",
  },
  {
    no: "14",
    id: "B0014",
    judul: "eu, eleifend nec,",
    pengarang: "Kylan Baird",
    penerbit: "Vel Mauris Associates",
    tahun: "2022",
  },
  {
    no: "15",
    id: "B0015",
    judul: "Sed eget lacus.",
    pengarang: "Jessica Hess",
    penerbit: "Quam Curabitur LLP",
    tahun: "2022",
  },
  {
    no: "16",
    id: "B0016",
    judul: "et, magna. Praesent",
    pengarang: "Teagan Ferrell",
    penerbit: "Massa Associates",
    tahun: "2022",
  },
  {
    no: "17",
    id: "B0017",
    judul: "libero et tristique",
    pengarang: "Ross Mcbride",
    penerbit: "Libero Incorporated",
    tahun: "2022",
  },
  {
    no: "18",
    id: "B0018",
    judul: "Aenean massa. Integer",
    pengarang: "Pascale Thornton",
    penerbit: "Ante Dictum Foundation",
    tahun: "2022",
  },
  {
    no: "19",
    id: "B0019",
    judul: "Nullam feugiat placerat",
    pengarang: "Madonna Brown",
    penerbit: "Mauris Nulla Inc.",
    tahun: "2022",
  },
  {
    no: "20",
    id: "B00020",
    judul: "tortor, dictum eu,",
    pengarang: "Burke Pacheco",
    penerbit: "Torquent Per Foundation",
    tahun: "2022",
  },
  {
    no: "21",
    id: "B00021",
    judul: "tortor, dictum eu,",
    pengarang: "Burke Pacheco",
    penerbit: "Torquent Per Foundation",
    tahun: "2022",
  },
];
